[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP server implementation for time calculation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]",
    "pytz",
]
